# org: chafikyassine
app: onlycoachs
service: onlycoachs-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ${opt:region, 'eu-west-3'}
  stage: ${opt:stage, 'dev'}
  memorySize: 512
  timeout: 6
  logRetentionInDays: 7

  apiGateway:
    shouldStartNameWithService: true # for upcoming Serverless v3

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  serverless-offline:
    useChildProcesses: true
    noPrependStageInUrl: true
    httpPort: 9000
    lambdaPort: 9002

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  graphql:
    handler: handler.graphql
    events:
      - httpApi:
          path: /graphql
          method: post
