# org: chafikyassine
app: onlycoachs-api
service: onlycoachs-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-3

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  graphql:
    handler: handler.graphql
    events:
      - httpApi:
          path: /graphql
          method: post

plugins:
  - serverless-plugin-typescript
